### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer

### ISSUE THREAD

**Issue by Lenzelot** [pdftk-java/pdftk-java-container#8]
Hello there,
I just tried out the pdftk:edge docker image to get an easily deployable version of the latest pdftk, but it is running into this exception upon running.

I tried this:

```
$ docker run --rm --volume $(pwd):/work pdftk/pdftk:edge large.pdf update_info_utf8 large.dump output large_meta.pdf
Unable to find image 'pdftk/pdftk:edge' locally
edge: Pulling from pdftk/pdftk
96526aa774ef: Pull complete
c1e35dd5d9c7: Pull complete
9bfc9ff2b6ab: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:082bb56f3255655b376112c167764029b5ca60882984cd320f7e3b9a27a24ceb
Status: Downloaded newer image for pdftk/pdftk:edge
Error: Unexpected Exception in open_reader()
Unhandled Java Exception in main():
java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.MappedRandomAccessFile.seek(MappedRandomAccessFile.java:166)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.RandomAccessFileOrArray.seek(RandomAccessFileOrArray.java:374)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.RandomAccessFileOrArray.setStartOffset(RandomAccessFileOrArray.java:680)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PRTokeniser.checkPdfHeader(PRTokeniser.java:191)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:493)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:172)
        at com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:161)
        at com.gitlab.pdftk_java.InputPdf.add_reader(InputPdf.java:73)
        at com.gitlab.pdftk_java.TK_Session.add_reader(TK_Session.java:61)
        at com.gitlab.pdftk_java.TK_Session.open_input_pdf_readers(TK_Session.java:78)
        at com.gitlab.pdftk_java.TK_Session$Parser.parse_state_output_filename(TK_Session.java:854)
        at com.gitlab.pdftk_java.TK_Session$Parser.parse(TK_Session.java:209)
        at com.gitlab.pdftk_java.TK_Session.parse(TK_Session.java:1112)
        at com.gitlab.pdftk_java.pdftk.main_noexit(pdftk.java:184)
        at com.gitlab.pdftk_java.pdftk.main(pdftk.java:161)
There was a problem with pdftk-java. Please report it at
https://gitlab.com/pdftk-java/pdftk/issues
including the message above, the version of pdftk-java (3.3.3), and if possible steps to reproduce the error.
```

Then tried to build my own image but the outcome is the same.

`docker build --build-arg COMMIT=master --tag=pdftk:20231025 .`

Is it possible that something is broken there? There were a lot of recent commits in pdftk-java and the aur package pdftk-git seems to work.

**Comment by robert-scheck** [comment]
Thank you for the report, nice catch! Thanks to https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/, I learned that `apk --no-cache add git apache-ant maven openjdk8-jre-base` installs openjdk17-jre-headless during build-time, which is most likely preferred over openjdk8-jre-base. Unfortunately this is not (yet) catched by the existing tests, because they are run directly after build of the `*.jar`, not for the final image.

**Comment by Lenzelot** [comment]
Works now. Thanks so much for your quick fix!
